name: Hello World workflow
run-name: Triggered by @${{ github.actor }}
on: 
 - push
 - workflow_dispatch

jobs:
   hello-job:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hello world"
   bye-job:
     runs-on: ubuntu-latest
     steps:
       - run: exit 1
         name: Bye-job-step1
       - run: echo "Bye world"
         name: Bye-job-step2
